use axum::extract::State;
use axum::http::HeaderMap;
use axum::response::{IntoResponse, Redirect, Response};
use maud::{Markup, html};

use crate::AppState;
use crate::handlers::admin::helpers::{
    bad_request, format_msk_iso, internal_error, render_page, set_display_tz_cache,
    theme_accent_lang,
};
use crate::handlers::admin::legacy::detail_tabs;
use crate::http_util::{form_field, path_segment_encode};
use vpnctl_core::humanize::format_size_bytes;

use super::backups::settings_disaster_recovery_section;
use super::system::settings_geoip_section;

/// `POST /admin/settings/timezone` — operator picks an IANA TZ
/// name from the Settings dropdown (2026-05-23). Validates the
/// name parses as `chrono_tz::Tz`, writes to inventory + updates
/// the global cache so subsequent renders see the new zone
/// without a daemon restart.
pub(crate) async fn settings_timezone_set(State(state): State<AppState>, body: String) -> Response {
    let tz_name = form_field(&body, "tz").unwrap_or_default();
    if tz_name.is_empty() {
        return bad_request("missing `tz` field");
    }
    let tz: chrono_tz::Tz = match tz_name.parse() {
        Ok(t) => t,
        Err(_) => {
            return bad_request(&format!(
                "'{tz_name}' is not a valid IANA timezone name (e.g. 'Europe/Moscow', 'UTC', 'America/New_York')"
            ));
        }
    };
    // Persist to DB FIRST — then update cache. If the write fails
    // we want the cache to still reflect the actually-stored value.
    if let Err(e) = state.inv.set_display_timezone(&tz_name).await {
        return internal_error(anyhow::Error::new(e));
    }
    set_display_tz_cache(tz);
    // Audit row for the timeline.
    if let Err(e) = state
        .inv
        .audit(
            "admin",
            "settings.timezone.set",
            Some("display"),
            Some(&serde_json::json!({ "timezone": tz_name })),
        )
        .await
    {
        tracing::warn!(
            target = "vpnctld::admin",
            error = %e,
            "audit row for settings.timezone.set failed; mutation already committed"
        );
    }
    Redirect::to("/admin/settings/appearance#timezone-section").into_response()
}

/// settings' in-page tabs (ui-audit §5 Phase 3). Same recipe as
/// `ServerTab`/`UserTab`: real sub-routes (`/admin/settings/{slug}`),\
/// plain `<a href>` links, each tab renders only its own sections.
/// `Appearance` is the default (bare `/admin/settings`).
#[derive(Clone, Copy, PartialEq, Eq)]
pub(crate) enum SettingsTab {
    Appearance,
    Backups,
    Notifications,
    System,
}

impl SettingsTab {
    fn slug(self) -> &'static str {
        match self {
            SettingsTab::Appearance => "appearance",
            SettingsTab::Backups => "backups",
            SettingsTab::Notifications => "notifications",
            SettingsTab::System => "system",
        }
    }
}

// Thin axum handlers — one per tab route in app.rs. Bare
// `/admin/settings` (+ trailing slash) + `/appearance` both land here.
pub(crate) async fn settings(headers: HeaderMap, State(state): State<AppState>) -> Markup {
    settings_render(headers, state, SettingsTab::Appearance).await
}

pub(crate) async fn settings_backups(headers: HeaderMap, State(state): State<AppState>) -> Markup {
    settings_render(headers, state, SettingsTab::Backups).await
}

pub(crate) async fn settings_notifications(
    headers: HeaderMap,
    State(state): State<AppState>,
) -> Markup {
    settings_render(headers, state, SettingsTab::Notifications).await
}

pub(crate) async fn settings_system(headers: HeaderMap, State(state): State<AppState>) -> Markup {
    settings_render(headers, state, SettingsTab::System).await
}

async fn settings_render(headers: HeaderMap, state: AppState, tab: SettingsTab) -> Markup {
    let (theme, accent, lang) = theme_accent_lang(&headers);
    // Auto-generated by vpnctld on startup (see
    // `crate::app::DEFAULT_DEPLOY_KEY_PATH` + `ensure_deploy_key`).
    // Surfaces the public half for diagnostic / out-of-inventory
    // paste. In-inventory servers should use the «push deploy key»
    // button on the server-detail page — the daemon handles SSH
    // itself, no manual editing required.
    let deploy_key_path = std::path::Path::new(crate::app::DEFAULT_DEPLOY_KEY_PATH);
    let deploy_pubkey =
        crate::ssh_subprocess::read_public_key(deploy_key_path).map_err(|e| e.to_string());

    // Phase C-4 — inventory snapshots. Reads the canonical backup
    // dir (same path the scheduler writes to). Listing failure is
    // shown inline rather than 500-ing — the rest of Settings
    // (theme, deploy key) should still render.
    let backup_dir = std::path::PathBuf::from(crate::app::DEFAULT_BACKUP_DIR);
    let snapshots = vpnctl_inventory::list_snapshots(&backup_dir).map_err(|e| e.to_string());

    // Phase 5e — Disaster recovery section pulls the LATEST
    // `backup.self_test` audit row to show last drill result inline.
    // Filtered SQL query (audit 2026-06-10): the old in-memory scan of
    // `recent_audit(50)` went blind within ~2 days — the hourly
    // `backup.snapshot` scheduler writes 24 rows/day, evicting the
    // self-test row from the last-50 window and rendering a false
    // «Never run».
    let last_self_test = state
        .inv
        .recent_audit_paginated(1, 0, None, Some("backup.self_test"), None, None)
        .await
        .ok()
        .and_then(|rows| rows.into_iter().next());

    // 2026-05-23 — display timezone (migration 0027). Render the
    // current setting in the dropdown's selected state. Failure to
    // read = use the default; doesn't break the rest of Settings.
    let display_tz_current = state
        .inv
        .get_display_timezone()
        .await
        .unwrap_or_else(|_| "Europe/Moscow".into());

    // Phase G chunk 3 — push notification transport config (Telegram
    // bot). Failure to read = render «(failed: …)» inline; don't
    // poison the rest of Settings.
    let telegram_cfg = state
        .inv
        .get_telegram_config()
        .await
        .map_err(|e| e.to_string());

    // Phase G chunk 3.5 — list inventory servers for the «proxy via»
    // dropdown. If the listing fails the dropdown shows only the
    // «direct» option (empty Vec) + the rest of Settings still renders.
    let servers_for_proxy_dropdown = state.inv.list_servers().await.unwrap_or_default();

    // v2 6a — one-glance «is the Telegram sink live» flag for the
    // System facts table (token AND chat id both set).
    let telegram_configured = matches!(
        telegram_cfg.as_ref(),
        Ok(Some(c)) if c.token.is_some() && c.chat_id.is_some()
    );

    let body = html! {
            div.ed-art-eyebrow { (crate::i18n::t(lang, crate::i18n::K::PageSettings)) }
            h1.ed-art-h1 {
                (crate::i18n::tr(lang, "homelab ", "homelab "))
                em { (crate::i18n::tr(lang, "controls", "управление")) }
            }
            p.ed-art-deck {
                (crate::i18n::tr(
                    lang,
                    "Daemon-wide knobs live here. Server / user mutations live on their respective pages.",
                    "Здесь лежат настройки уровня всего демона. Изменения серверов / пользователей — на их собственных страницах.",
                ))
            }

    (detail_tabs("/admin/settings", tab.slug(), &[("appearance", crate::i18n::tr(lang, "Appearance", "Внешний вид")), ("backups", crate::i18n::tr(lang, "Backups", "Бэкапы")), ("notifications", crate::i18n::tr(lang, "Notifications", "Уведомления")), ("system", crate::i18n::tr(lang, "System", "Система"))]))
    @if tab == SettingsTab::Appearance {
            // No ed-rule here — the tab row above already draws its own
            // bottom border; stacking both produced a double line
            // (design review 2026-07-10).
            div.ed-art-eyebrow style="margin-top: 14px;" { (crate::i18n::tr(lang, "Appearance — theme + accent", "Внешний вид — тема + акцент")) }
            p style="font-family: var(--serif); font-style: italic; font-size: 12px; color: var(--mute); margin: 6px 0 12px;" {
                (crate::i18n::tr(
                    lang,
                    "Pick a paper theme (background palette) and an accent colour. Choices are stored as cookies; one-time configuration.",
                    "Выбери бумажную тему (фон) и акцентный цвет. Сохраняется в cookies; настраивается один раз.",
                ))
            }
            (crate::handlers::admin::legacy::shell::tweaks_inline(&theme, &accent, lang))

            div.ed-rule {}
            div #timezone-section {
                div.ed-art-eyebrow {
                    (crate::i18n::tr(lang, "Display timezone", "Часовой пояс отображения"))
                }
                p style="font-family: var(--serif); font-style: italic; font-size: 12px; color: var(--mute); margin: 6px 0 12px;" {
                    (crate::i18n::tr(
                        lang,
                        "Every operator-visible timestamp (alerts feed, audit timeline, sub-access log, chart axis labels, …) is rendered in this timezone with its UPPERCASE abbreviation suffix (e.g. ",
                        "Каждая видимая оператору метка времени (лента alerts, audit, sub-access лог, подписи осей графиков, …) рендерится в этом часовом поясе с прописной аббревиатурой (например ",
                    ))
                    span.ed-mono { "MSK" } ", " span.ed-mono { "UTC" } ", " span.ed-mono { "EST" }
                    (crate::i18n::tr(
                        lang,
                        "). Pick an IANA timezone name; full database (incl. DST rules) is bundled.",
                        "). Выбери IANA-имя часового пояса; полная база (включая DST) встроена.",
                    ))
                }
                form method="post"
                     action="/admin/settings/timezone"
                     style="display: flex; gap: 8px; align-items: baseline;" {
                    label style="font-family: var(--mono); font-size: 11px; color: var(--mute); text-transform: uppercase; letter-spacing: 0.10em;" {
                        (crate::i18n::tr(lang, "timezone", "часовой пояс"))
                    }
                    @let common_tzs: &[&str] = &[
                        "UTC",
                        "Europe/Moscow",
                        "Europe/London",
                        "Europe/Berlin",
                        "Europe/Helsinki",
                        "Europe/Istanbul",
                        "Asia/Dubai",
                        "Asia/Tbilisi",
                        "Asia/Bangkok",
                        "Asia/Shanghai",
                        "Asia/Tokyo",
                        "America/New_York",
                        "America/Los_Angeles",
                    ];
                    select name="tz"
                           style="padding: 4px 8px; border: 1px solid var(--rule-s); background: var(--paper); font-family: var(--mono); font-size: 12px; color: var(--ink); min-width: 220px;" {
                        @for tz in common_tzs {
                            @if *tz == display_tz_current.as_str() {
                                option value=(tz) selected="selected" { (tz) }
                            } @else {
                                option value=(tz) { (tz) }
                            }
                        }
                        // If current value isn't in the common list,
                        // surface it as a selected option at the end so
                        // the operator can keep it without retyping.
                        @if !common_tzs.contains(&display_tz_current.as_str()) {
                            option value=(display_tz_current) selected="selected" {
                                (display_tz_current) " (custom)"
                            }
                        }
                    }
                    button type="submit"
                           style="padding: 4px 12px; border: 1px solid var(--accent); background: var(--accent); color: var(--paper); font-family: var(--mono); font-size: 11px; cursor: pointer;" {
                        (crate::i18n::tr(lang, "save", "сохранить"))
                    }
                    span style="font-family: var(--serif); font-style: italic; font-size: 12px; color: var(--mute);" {
                        (crate::i18n::tr(
                            lang,
                            "→ takes effect on the next page render (no restart needed)",
                            "→ применится при следующем рендере страницы (рестарт не нужен)",
                        ))
                    }
                }
            }

    }
    @if tab == SettingsTab::Backups {
            // No ed-rule — the tab row draws its own bottom border (R2).
            div #backups-section.ed-art-eyebrow style="margin-top: 14px;" {
                (crate::i18n::tr(lang, "Backups — inventory snapshots", "Бэкапы — снэпшоты инвентаря"))
            }
            p style="font-family: var(--serif); font-style: italic; font-size: 12px; color: var(--mute); margin: 6px 0 14px;" {
                (crate::i18n::tr(lang, "vpnctld snapshots ", "vpnctld делает снэпшоты "))
                span.ed-mono { (crate::app::DEFAULT_DEPLOY_KEY_PATH.replace("/.ssh/id_ed25519", "/inv.db")) }
                (crate::i18n::tr(lang, " hourly into ", " ежечасно в "))
                span.ed-mono { (crate::app::DEFAULT_BACKUP_DIR) }
                (crate::i18n::tr(
                    lang,
                    " (24 hourly + 30 daily + 12 monthly retained). ",
                    " (хранятся 24 часовых + 30 дневных + 12 месячных). ",
                ))
                b { (crate::i18n::tr(lang, "Off-site is operator-driven", "Off-site копии делает оператор")) }
                (crate::i18n::tr(lang, " — click ", " — кликни "))
                em { (crate::i18n::tr(lang, "download", "скачать")) }
                (crate::i18n::tr(
                    lang,
                    " next to a snapshot and copy it to USB / Forgejo / cloud / wherever you trust. The daemon never pushes anywhere by itself.",
                    " рядом со снэпшотом и скопируй на USB / Forgejo / облако / куда доверяешь. Демон сам никуда не пушит.",
                ))
            }
            div style="display: flex; gap: 12px; align-items: center; margin-bottom: 14px; flex-wrap: wrap;" {
                form method="post" action="/admin/backup/snapshot" style="display: inline;" {
                    button type="submit"
                           title=(crate::i18n::tr(
                               lang,
                               "Take a snapshot now (in addition to the hourly schedule). Safe to click any time.",
                               "Сделать снэпшот сейчас (вдобавок к часовому расписанию). Безопасно нажимать в любой момент.",
                           ))
                           class="ed-abtn ed-abtn--secondary ed-abtn--lg" {
                        (crate::i18n::tr(lang, "snapshot now", "снэпшот сейчас"))
                    }
                }
                // Phase 5c — restore self-test button. Operator clicks →
                // verify_snapshot runs against the latest snapshot in a
                // tempdir → /admin/backup/self-test renders a pass/fail
                // HTML report (no SSE — completes in <1s for our DB size).
                form method="post" action="/admin/backup/self-test" style="display: inline;" {
                    button type="submit"
                           title=(crate::i18n::tr(
                               lang,
                               "Run restore fire-drill against the latest snapshot — does it actually restore into a usable DB? Safe to click any time; does NOT touch live inv.db.",
                               "Запустить проверку восстановления на последнем снэпшоте — реально ли он восстанавливается в рабочую БД? Безопасно нажимать в любой момент; живую inv.db не трогает.",
                           ))
                           class="ed-abtn ed-abtn--recovery ed-abtn--lg" {
                        (crate::i18n::tr(lang, "run restore self-test", "проверить восстановление"))
                    }
                }
                span style="font-family: var(--serif); font-style: italic; font-size: 12px; color: var(--mute);" {
                    (crate::i18n::tr(
                        lang,
                        "Restore-in-place is a CLI command (the daemon's restore subcommand — it can't replace its own open DB). The self-test above proves the snapshot WOULD restore, without touching the live DB.",
                        "Восстановление поверх живой БД — это CLI-команда (подкоманда restore демона — он не может заменить свою же открытую БД). Self-test выше доказывает что снэпшот ВОССТАНОВИТСЯ, не трогая живую БД.",
                    ))
                }
            }
            @match snapshots {
                Ok(list) if list.is_empty() => {
                    p style="font-family: var(--serif); font-style: italic; color: var(--mute); font-size: 12px;" {
                        (crate::i18n::tr(
                            lang,
                            "No snapshots yet. The scheduler fires its first snapshot ~60 seconds after daemon start; click ",
                            "Снэпшотов пока нет. Шедулер делает первый ~60 секунд после старта демона; кликни ",
                        ))
                        b { (crate::i18n::tr(lang, "snapshot now", "снэпшот сейчас")) }
                        (crate::i18n::tr(lang, " above to skip the wait.", " выше чтобы не ждать."))
                    }
                }
                Ok(list) => {
                    // Scrollable container so a 60-row backlog at the
                    // retention policy's cap doesn't push the rest of
                    // Settings (Deploy key, Telegram, etc) several
                    // viewport-heights down. Sticky header keeps the
                    // column labels visible while scrolling.
                    div style="max-height: 360px; overflow-y: auto; border: 1px solid var(--rule);" {
                        table style="width: 100%; border-collapse: collapse; font-family: var(--mono); font-size: 11px;" {
                            thead style="position: sticky; top: 0; background: var(--paper); z-index: 1;" {
                                tr {
                                    th style="text-align: left; padding: 6px 8px; border-bottom: 1px solid var(--rule); color: var(--mute); font-weight: normal; letter-spacing: 0.10em; text-transform: uppercase; font-size: 10px;" {
                                        (crate::i18n::tr(lang, "created", "создан"))
                                    }
                                    th style="text-align: right; padding: 6px 8px; border-bottom: 1px solid var(--rule); color: var(--mute); font-weight: normal; letter-spacing: 0.10em; text-transform: uppercase; font-size: 10px;" {
                                        (crate::i18n::tr(lang, "size", "размер"))
                                    }
                                    th style="text-align: left; padding: 6px 8px; border-bottom: 1px solid var(--rule); color: var(--mute); font-weight: normal; letter-spacing: 0.10em; text-transform: uppercase; font-size: 10px;" {
                                        (crate::i18n::tr(lang, "action", "действие"))
                                    }
                                }
                            }
                            tbody {
                                @for snap in list.iter().take(60) {
                                    tr {
                                        td style="padding: 4px 8px; border-bottom: 1px dotted var(--rule);" {
                                            // R2 2026-07-10: the display timezone applies here
                                            // like everywhere else; a filename that doesn't
                                            // carry a parseable stamp shows the NAME instead of
                                            // a «(unparseable timestamp)» parser complaint.
                                            @match snap
                                                .created
                                                .as_deref()
                                                .and_then(|s| chrono::DateTime::parse_from_rfc3339(s).ok())
                                            {
                                                Some(ts) => (format_msk_iso(ts.with_timezone(&chrono::Utc))),
                                                None => span.ed-grid__mut
                                                    title=(crate::i18n::tr(
                                                        lang,
                                                        "No timestamp in the filename (manual or legacy snapshot) — shown by name.",
                                                        "В имени файла нет метки времени (ручной или легаси-снэпшот) — показан по имени.",
                                                    )) {
                                                    (snap.file_name)
                                                },
                                            }
                                        }
                                        td style="padding: 4px 8px; border-bottom: 1px dotted var(--rule); text-align: right; color: var(--soft);" {
                                            (format_size_bytes(snap.size_bytes))
                                        }
                                        td style="padding: 4px 8px; border-bottom: 1px dotted var(--rule);" {
                                            a href=(format!("/admin/backup/download/{}", path_segment_encode(&snap.file_name)))
                                               download=(&snap.file_name)
                                               title=(crate::i18n::tr(
                                                   lang,
                                                   "Save this snapshot to your local disk for off-site storage",
                                                   "Скачать этот снэпшот на локальный диск для off-site хранения",
                                               ))
                                               style="color: var(--ink); text-decoration: underline;" {
                                                (crate::i18n::tr(lang, "download", "скачать"))
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                    @if list.len() > 60 {
                        p style="font-family: var(--serif); font-style: italic; color: var(--mute); font-size: 11px; margin-top: 8px;" {
                            "(" (list.len() - 60)
                            @if list.len() - 60 != 1 {
                                (crate::i18n::tr(lang, " older snapshots hidden", " более старых снэпшотов скрыто"))
                            } @else {
                                (crate::i18n::tr(lang, " older snapshot hidden", " более старый снэпшот скрыт"))
                            }
                            (crate::i18n::tr(
                                lang,
                                " — the retention policy caps total count, so the table won't grow unbounded.)",
                                " — политика хранения ограничивает количество, таблица не растёт бесконечно.)",
                            ))
                        }
                    }
                }
                Err(e) => {
                    p style="font-family: var(--serif); font-style: italic; color: var(--red); font-size: 12px;" {
                        (crate::i18n::tr(lang, "Can't list snapshots in ", "Не удалось перечислить снэпшоты в "))
                        span.ed-mono { (crate::app::DEFAULT_BACKUP_DIR) }
                        ": " (e)
                        (crate::i18n::tr(
                            lang,
                            ". Most likely the daemon user doesn't have access — check the permissions on the daemon's data directory.",
                            ". Скорее всего у пользователя демона нет доступа — проверь права на каталог данных демона.",
                        ))
                    }
                }
            }

            (settings_disaster_recovery_section(lang, last_self_test.as_ref()))

    }
    @if tab == SettingsTab::Notifications {
            // No ed-rule — the tab row draws its own bottom border (R2).
            // `id` so the POST-redirect-GET after Save can use a
            // fragment anchor (`#telegram-notifications`) and the
            // browser scrolls back to this section instead of jumping
            // to the top of /admin/settings.
            div #telegram-notifications.ed-art-eyebrow style="margin-top: 14px;" {
                (crate::i18n::tr(
                    lang,
                    "Notifications — Telegram bot",
                    "Уведомления — Telegram-бот",
                ))
            }
            p style="font-family: var(--serif); font-style: italic; font-size: 12px; color: var(--mute); margin: 6px 0 14px;" {
                (crate::i18n::tr(
                    lang,
                    "When an alert fires (probe-detector or service flip), vpnctld POSTs a one-line message to a Telegram chat via ",
                    "Когда срабатывает алерт (probe-detector или поднятие/падение сервиса), vpnctld POST-ит однострочное сообщение в Telegram-чат через ",
                ))
                span.ed-mono { "api.telegram.org/bot<token>/sendMessage" }
                (crate::i18n::tr(
                    lang,
                    ". One operator, one chat — paste the bot token and your numeric chat-id below. Create the bot via ",
                    ". Один оператор, один чат — вставь bot-токен и свой числовой chat-id ниже. Создай бота через ",
                ))
                span.ed-mono { "@BotFather" }
                (crate::i18n::tr(lang, " on Telegram; get your chat-id by messaging ", " в Telegram; узнай свой chat-id написав "))
                span.ed-mono { "@userinfobot" }
                ". "
                b { (crate::i18n::tr(lang, "The token is a secret", "Токен — секрет")) }
                (crate::i18n::tr(lang, " — stored in ", " — хранится в "))
                span.ed-mono { "/var/lib/vpnctl/inv.db" }
                (crate::i18n::tr(
                    lang,
                    " (daemon-owned 0640), masked in this page after save. Clear both fields and re-save to disable.",
                    " (демон-only 0640), маскируется на этой странице после сохранения. Очисти оба поля и сохрани снова чтобы отключить.",
                ))
            }

            // Status line — tells the operator at a glance whether the
            // transport is wired. Three branches: config read failed,
            // both fields set ("enabled"), or partial/none ("disabled").
            @match &telegram_cfg {
                Err(e) => {
                    p style="font-family: var(--serif); font-style: italic; color: var(--red); font-size: 12px;" {
                        (crate::i18n::tr(lang, "Can't read notification settings: ", "Не удалось прочитать настройки уведомлений: ")) (e)
                    }
                }
                Ok(None) => {
                    p style="font-family: var(--serif); font-style: italic; color: var(--red); font-size: 12px;" {
                        (crate::i18n::tr(
                            lang,
                            "Settings row missing — migration 0014 didn't seed it. Daemon restart should re-run migrations.",
                            "Строка settings отсутствует — миграция 0014 не записала её. Перезапуск демона прогонит миграции заново.",
                        ))
                    }
                }
                Ok(Some(cfg)) if cfg.is_enabled() => {
                    p style="font-family: var(--mono); font-size: 12px; color: var(--ink); margin: 0 0 10px;" {
                        (crate::i18n::tr(lang, "Status: ", "Статус: ")) b { (crate::i18n::tr(lang, "enabled", "включено")) }
                        (crate::i18n::tr(lang, " · token ", " · токен "))
                        span style="color: var(--mute);" { "••••" (cfg.token_last4()) }
                        (crate::i18n::tr(lang, " · chat ", " · чат "))
                        span style="color: var(--mute);" { (cfg.chat_id.as_deref().unwrap_or("")) }
                    }
                }
                Ok(Some(cfg)) if cfg.token.is_some() || cfg.chat_id.is_some() => {
                    @let which_missing = if cfg.token.is_none() {
                        crate::i18n::tr(lang, "bot token", "bot-токен")
                    } else {
                        crate::i18n::tr(lang, "chat-id", "chat-id")
                    };
                    p style="font-family: var(--mono); font-size: 12px; color: var(--red); margin: 0 0 10px;" {
                        (crate::i18n::tr(lang, "Status: ", "Статус: ")) b { (crate::i18n::tr(lang, "partial config", "конфиг неполный")) }
                        " — " (which_missing)
                        (crate::i18n::tr(
                            lang,
                            " missing, transport effectively disabled. Fill in the missing field below + save, OR clear both fields to fully reset.",
                            " отсутствует, транспорт фактически выключен. Заполни недостающее поле ниже + сохрани, ЛИБО очисти оба чтобы сбросить.",
                        ))
                    }
                }
                Ok(Some(_)) => {
                    p style="font-family: var(--mono); font-size: 12px; color: var(--mute); margin: 0 0 10px;" {
                        (crate::i18n::tr(lang, "Status: ", "Статус: "))
                        b style="color: var(--ink);" { (crate::i18n::tr(lang, "disabled", "выключено")) }
                        (crate::i18n::tr(lang, " — fill in both fields below + save.", " — заполни оба поля ниже + сохрани."))
                    }
                }
            }

            form method="post" action="/admin/settings/telegram" style="margin: 0 0 14px;" {
                div style="display: grid; grid-template-columns: 140px 1fr; gap: 10px 14px; align-items: center; max-width: 720px;" {
                    label for="telegram_bot_token" style="font-family: var(--mono); font-size: 11px; color: var(--mute);" {
                        (crate::i18n::tr(lang, "bot token", "bot-токен"))
                    }
                    input type="password"
                          id="telegram_bot_token"
                          name="telegram_bot_token"
                          // R2: the old placeholder was a three-clause
                          // manual that truncated at narrower widths —
                          // the full rules live in the tooltip.
                          placeholder=(crate::i18n::tr(
                              lang,
                              "blank = keep existing",
                              "пусто = оставить как есть",
                          ))
                          autocomplete="off"
                          title=(crate::i18n::tr(
                              lang,
                              "Token from @BotFather, shape `123456:ABC-XYZ...`. Stored in inv.db, masked after save. Leave blank to keep the existing token; paste a new value to replace it; clear BOTH fields and save to disable the Telegram sink entirely.",
                              "Токен от @BotFather, форма `123456:ABC-XYZ...`. Хранится в inv.db, маскируется после сохранения. Пусто = оставить текущий; новое значение = заменить; очистить ОБА поля и сохранить = полностью выключить Telegram.",
                          ))
                          style="font-family: var(--mono); font-size: 12px; padding: 5px 8px; border: 1px solid var(--rule); background: var(--paper);";
                    label for="telegram_chat_id" style="font-family: var(--mono); font-size: 11px; color: var(--mute);" {
                        (crate::i18n::tr(lang, "chat-id", "chat-id"))
                    }
                    input type="text"
                          id="telegram_chat_id"
                          name="telegram_chat_id"
                          value=(match &telegram_cfg {
                              Ok(Some(cfg)) => cfg.chat_id.as_deref().unwrap_or(""),
                              _ => "",
                          })
                          placeholder=(crate::i18n::tr(
                              lang,
                              "numeric, e.g. 123456789 (or @your_channel)",
                              "число, напр. 123456789 (или @your_channel)",
                          ))
                          title=(crate::i18n::tr(
                              lang,
                              "Numeric user/group id from @userinfobot OR a public @channel handle. Test-send button below checks this end-to-end.",
                              "Числовой user/group id от @userinfobot ИЛИ публичный @channel-хэндл. Кнопка тестового сообщения ниже проверяет всю цепочку.",
                          ))
                          style="font-family: var(--mono); font-size: 12px; padding: 5px 8px; border: 1px solid var(--rule); background: var(--paper);";

                    label for="proxy_via_server_id" style="font-family: var(--mono); font-size: 11px; color: var(--mute);" {
                        (crate::i18n::tr(lang, "egress", "выход"))
                    }
                    @let current_proxy_id: &str = match &telegram_cfg {
                        Ok(Some(cfg)) => cfg.proxy_via_server_id.as_deref().unwrap_or(""),
                        _ => "",
                    };
                    select name="proxy_via_server_id"
                           id="proxy_via_server_id"
                           title=(crate::i18n::tr(
                               lang,
                               "If the daemon host can't reach api.telegram.org directly (РФ blocks, NAT, etc), route the call through an inventory server's network instead. Uses the existing deploy SSH key — the public half must be on root@<proxy-server>:~/.ssh/authorized_keys (see «Deploy SSH key» section below to copy).",
                               "Если хост демона не может достучаться до api.telegram.org напрямую (блоки РФ, NAT и т.п.), направь вызов через сеть одного из серверов инвентаря. Использует существующий deploy SSH-ключ — его публичная половина должна быть на root@<proxy-server>:~/.ssh/authorized_keys (см. секцию «Deploy SSH key» ниже).",
                           ))
                           style="font-family: var(--mono); font-size: 12px; padding: 5px 8px; border: 1px solid var(--rule); background: var(--paper);" {
                        option value="" selected[current_proxy_id.is_empty()] {
                            (crate::i18n::tr(lang, "direct (local network)", "напрямую (локальная сеть)"))
                        }
                        @for s in &servers_for_proxy_dropdown {
                            option value=(s.id.0) selected[current_proxy_id == s.id.0] {
                                (crate::i18n::tr(lang, "via server: ", "через сервер: ")) (s.id.0) " (" (s.address) ")"
                            }
                        }
                    }
                }

                @if servers_for_proxy_dropdown.is_empty() {
                    p style="font-family: var(--serif); font-style: italic; font-size: 12px; color: var(--mute); margin: 8px 0 0; max-width: 720px;" {
                        (crate::i18n::tr(lang, "No servers in inventory yet — only ", "Серверов в инвентаре пока нет — доступен только "))
                        b { (crate::i18n::tr(lang, "direct", "напрямую")) }
                        (crate::i18n::tr(lang, " egress is available. Add a server on ", " выход. Добавь сервер на "))
                        span.ed-mono { "/admin/servers" }
                        (crate::i18n::tr(lang, " first if your daemon host can't reach ", " если хост демона не достучивается до "))
                        span.ed-mono { "api.telegram.org" } "."
                    }
                } @else {
                    p style="font-family: var(--serif); font-style: italic; font-size: 12px; color: var(--mute); margin: 8px 0 0; max-width: 720px;" {
                        (crate::i18n::tr(lang, "Picking a ", "Выбор опции "))
                        b { (crate::i18n::tr(lang, "via server: …", "через сервер: …")) }
                        (crate::i18n::tr(
                            lang,
                            " option requires the daemon's deploy SSH pubkey to be on that server's ",
                            " требует чтобы deploy SSH публичный ключ демона был в ",
                        ))
                        span.ed-mono { "~/.ssh/authorized_keys" }
                        (crate::i18n::tr(lang, ". The pubkey lives in the ", " этого сервера. Pubkey лежит в секции "))
                        a href="#deploy-ssh-key" style="color: var(--ink);" {
                            b { (crate::i18n::tr(lang, "Deploy SSH key", "Deploy SSH-ключ")) }
                        }
                        (crate::i18n::tr(
                            lang,
                            " section below — copy it once, then ",
                            " ниже — скопируй один раз, затем ",
                        ))
                        em { (crate::i18n::tr(lang, "send test message", "отправить тестовое сообщение")) }
                        (crate::i18n::tr(lang, " confirms the path works.", " подтвердит что путь работает."))
                    }
                }

                div style="margin-top: 12px;" {
                    button type="submit"
                           title=(crate::i18n::tr(
                               lang,
                               "Save all three fields. Empty token = keep existing (unless chat-id is ALSO empty, then clear). Empty chat-id = clear. Egress dropdown is always overwritten with the selected value.",
                               "Сохранить все три поля. Пустой токен = оставить как есть (если chat-id ТОЖЕ пуст, тогда очистить). Пустой chat-id = очистить. Egress dropdown всегда переписывается выбранным значением.",
                           ))
                           style="padding: 6px 14px; border: 1px solid var(--ink); background: var(--ink); color: var(--paper); font-family: var(--mono); font-size: 11px; cursor: pointer;" {
                        (crate::i18n::t(lang, crate::i18n::K::BtnSave))
                    }
                }
            }

            // Test-send button — separate form POSTing to /admin/settings/
            // telegram/test so the operator can verify their credentials
            // without waiting for an actual alert to fire. Disabled (greyed
            // out via inline disabled attr) when the transport isn't
            // currently enabled — same predicate the dispatch loop uses.
            @match &telegram_cfg {
                Ok(Some(cfg)) if cfg.is_enabled() => {
                    form method="post" action="/admin/settings/telegram/test" style="margin-top: 10px;" {
                        button type="submit"
                               title=(crate::i18n::tr(
                                   lang,
                                   "Send a test message to the configured chat. Surfaces curl / Telegram-API errors inline.",
                                   "Отправить тестовое сообщение в настроенный чат. Ошибки curl / Telegram-API показываются прямо здесь.",
                               ))
                               style="padding: 5px 12px; border: 1px solid var(--rule); background: var(--paper); color: var(--ink); font-family: var(--mono); font-size: 11px; cursor: pointer;" {
                            (crate::i18n::tr(lang, "send test message", "отправить тестовое сообщение"))
                        }
                        span style="font-family: var(--serif); font-style: italic; font-size: 12px; color: var(--mute); margin-left: 14px;" {
                            (crate::i18n::tr(
                                lang,
                                "Posts a «🟢 Telegram connected» sample in the real alert format + your chosen language.",
                                "Пошлёт пример «🟢 Telegram подключён» в реальном формате алертов и на выбранном языке.",
                            ))
                        }
                    }
                    // On-demand fleet digest (the daily scheduler sends it
                    // automatically; this is the «send it now» button).
                    form method="post" action="/admin/settings/digest-now" style="margin-top: 8px;" {
                        button type="submit"
                               title=(crate::i18n::tr(
                                   lang,
                                   "Send the fleet digest now: all-clear, or the list of open problems. Also sent daily.",
                                   "Отправить дайджест по флоту сейчас: всё спокойно или список открытых проблем. Также шлётся раз в сутки.",
                               ))
                               style="padding: 5px 12px; border: 1px solid var(--rule); background: var(--paper); color: var(--ink); font-family: var(--mono); font-size: 11px; cursor: pointer;" {
                            (crate::i18n::tr(lang, "send digest now", "отправить дайджест"))
                        }
                        span style="font-family: var(--serif); font-style: italic; font-size: 12px; color: var(--mute); margin-left: 14px;" {
                            (crate::i18n::tr(
                                lang,
                                "A daily summary is sent automatically; this sends one immediately.",
                                "Ежедневная сводка отправляется автоматически; эта кнопка шлёт её сразу.",
                            ))
                        }
                    }
                }
                _ => {
                    p style="font-family: var(--serif); font-style: italic; font-size: 12px; color: var(--mute); margin: 10px 0 0;" {
                        (crate::i18n::tr(
                            lang,
                            "Test-send button appears after both fields are saved + status is ",
                            "Кнопка тестового сообщения появится после сохранения обоих полей и когда статус ",
                        ))
                        b style="color: var(--ink);" { (crate::i18n::tr(lang, "enabled", "включено")) } "."
                    }
                }
            }

            // Notification language — operator-selectable locale for the
            // Telegram alert pushes. Independent of the per-browser admin-UI
            // [EN|RU] shell toggle: this one is persisted in
            // notification_settings.language + drives render_alert at push
            // time, so alerts speak the chosen language regardless of which
            // browser the operator reads /admin from.
            @let notif_lang = match &telegram_cfg {
                Ok(Some(cfg)) => crate::i18n::Locale::from_lang_code(cfg.language.as_deref()),
                _ => crate::i18n::Locale::En,
            };
            div style="margin-top: 18px;" {
                div.ed-art-eyebrow style="margin-bottom: 8px;" {
                    (crate::i18n::tr(lang, "Alert language", "Язык уведомлений"))
                }
                @for (code, label, is_active) in [
                    ("ru", "Русский", notif_lang == crate::i18n::Locale::Ru),
                    ("en", "English", notif_lang == crate::i18n::Locale::En),
                ] {
                    form method="post" action="/admin/settings/notification-language"
                         style="display: inline; margin: 0 8px 0 0;" {
                        input type="hidden" name="language" value=(code);
                        button type="submit" disabled[is_active]
                               style=(if is_active {
                                   "padding: 5px 12px; border: 1px solid var(--ink); background: var(--ink); color: var(--paper); font-family: var(--mono); font-size: 11px;"
                               } else {
                                   "padding: 5px 12px; border: 1px solid var(--rule); background: var(--paper); color: var(--ink); font-family: var(--mono); font-size: 11px; cursor: pointer;"
                               }) {
                            (label)
                        }
                    }
                }
                span style="font-family: var(--serif); font-style: italic; font-size: 12px; color: var(--mute); margin-left: 6px;" {
                    (crate::i18n::tr(
                        lang,
                        "Telegram alerts are sent in this language.",
                        "Алерты в Telegram приходят на этом языке.",
                    ))
                }
            }

    }
    @if tab == SettingsTab::System {
            // v2 6a — system facts table: the daemon's moving parts and
            // their cadence, one glance. Values come from the same env
            // knobs the pollers read; alert sink state from inventory.
            @let probe_min = std::env::var("VPNCTLD_NODE_PROBE_INTERVAL_SECS").ok()
                .and_then(|v| v.parse::<u64>().ok()).unwrap_or(600) / 60;
            @let clash_min = std::env::var("VPNCTLD_POLL_INTERVAL_SECS").ok()
                .and_then(|v| v.parse::<u64>().ok()).unwrap_or(300) / 60;
            div.ed-art-eyebrow { (crate::i18n::tr(lang, "System", "Система")) }
            table.ed-feed style="margin: 8px 0 16px;" {
                tbody {
                    tr {
                        td.ed-grid__mut style="width: 160px;" { (crate::i18n::tr(lang, "probe tick", "тик проб")) }
                        td { b { (probe_min) " " (crate::i18n::tr(lang, "min", "мин")) } }
                        td.num.ed-grid__mut.ed-grid__sm { "node_probe_poller · VPNCTLD_NODE_PROBE_INTERVAL_SECS" }
                    }
                    tr {
                        td.ed-grid__mut { (crate::i18n::tr(lang, "clash poll", "опрос clash")) }
                        td { b { (clash_min) " " (crate::i18n::tr(lang, "min", "мин")) } " · " (crate::i18n::tr(lang, "per-node traffic attribution", "атрибуция трафика по нодам")) }
                        td.num.ed-grid__mut.ed-grid__sm { "clash_poller · VPNCTLD_POLL_INTERVAL_SECS" }
                    }
                    tr {
                        td.ed-grid__mut { (crate::i18n::tr(lang, "alert sink", "канал алертов")) }
                        td {
                            "telegram "
                            @if telegram_configured {
                                b style="color: var(--green);" { "on" }
                            } @else {
                                b.ed-grid__mut { "off" }
                            }
                        }
                        td.num.ed-grid__mut.ed-grid__sm {
                            a href="/admin/settings/notifications" style="color: var(--acc);" {
                                (crate::i18n::tr(lang, "configure →", "настроить →"))
                            }
                        }
                    }
                    tr {
                        td.ed-grid__mut { (crate::i18n::tr(lang, "rate limit", "rate limit")) }
                        td.ed-grid__sm { "/sub + /api/v1/app/config · " (crate::i18n::tr(lang, "per-device + non-egress per-IP buckets", "пер-девайс + пер-IP (не-egress) бакеты")) }
                        td.num.ed-grid__mut.ed-grid__sm { "rate_limit.rs" }
                    }
                }
            }

            div.ed-rule {}
            (settings_geoip_section(lang))

            div.ed-rule {}
            div #deploy-ssh-key.ed-art-eyebrow {
                (crate::i18n::tr(lang, "Deploy SSH key", "Deploy SSH-ключ"))
            }
            p style="font-family: var(--serif); font-style: italic; font-size: 12px; color: var(--mute); margin: 6px 0 14px;" {
                (crate::i18n::tr(
                    lang,
                    "vpnctld auto-generated this Curve25519 keypair on first start. The private half stays in ",
                    "vpnctld сгенерировал эту Curve25519-пару при первом старте. Приватная половина остаётся в ",
                ))
                span.ed-mono { (crate::app::DEFAULT_DEPLOY_KEY_PATH) }
                (crate::i18n::tr(
                    lang,
                    " — never shown. The public half (below) goes into each VPN node's ",
                    " — никогда не показывается. Публичная половина (ниже) идёт в ",
                ))
                span.ed-mono { "~/.ssh/authorized_keys" }
                (crate::i18n::tr(lang, ". Once authorised, every ", " каждой VPN-ноды. Когда авторизован, каждый клик "))
                b { (crate::i18n::tr(lang, "deploy →", "деплой →")) }
                (crate::i18n::tr(
                    lang,
                    " button click pushes configs through vpnctld → ssh subprocess → node, no operator-typed CLI needed.",
                    " пушит конфиги по пути vpnctld → ssh-подпроцесс → нода, без ручных CLI-команд оператора.",
                ))
            }
            @match deploy_pubkey {
                Ok(pk) => {
                    pre style="font-family: var(--mono); font-size: 11px; padding: 12px 14px; background: var(--paper); border: 1px solid var(--rule); white-space: pre-wrap; word-break: break-all;" {
                        (pk)
                    }
                    p style="font-family: var(--serif); font-style: italic; font-size: 12px; color: var(--mute); margin: 8px 0 0;" {
                        (crate::i18n::tr(lang, "Authorise this key on a server via the ", "Авторизуй этот ключ на сервере через "))
                        a href="/admin/servers" style="color: var(--ink);" {
                            b { "/admin/servers" }
                        }
                        (crate::i18n::tr(lang, " list → pick a server → ", " → выбрать сервер → "))
                        span.ed-mono { (crate::i18n::tr(lang, "«Deploy SSH key — push to this server»", "«Deploy SSH key — push to this server»")) }
                        (crate::i18n::tr(lang, " section → ", " секция → "))
                        span.ed-mono { (crate::i18n::tr(lang, "«push deploy key»", "«push deploy key»")) }
                        (crate::i18n::tr(
                            lang,
                            " button. The daemon handles the SSH dance for you — no manual SSH login or ",
                            " кнопка. Демон делает SSH-танец сам — без ручного SSH-логина или редактирования ",
                        ))
                        span.ed-mono { "authorized_keys" }
                        (crate::i18n::tr(
                            lang,
                            " editing. The pubkey above is shown for diagnostic / out-of-band-paste use only (e.g. you want to authorise the key on something that ISN'T in vpnctl's inventory).",
                            " вручную. Pubkey выше показан только для диагностики / out-of-band вставки (например если ты хочешь авторизовать ключ на чём-то ВНЕ инвентаря vpnctl).",
                        ))
                    }
                }
                Err(e) => {
                    p style="font-family: var(--serif); font-style: italic; color: var(--red);" {
                        (crate::i18n::tr(lang, "Public key file unreadable: ", "Публичный ключ не читается: ")) (e)
                        (crate::i18n::tr(lang, ". Most common cause: ", ". Чаще всего: "))
                        span.ed-mono { "/var/lib/vpnctl/.ssh" }
                        (crate::i18n::tr(
                            lang,
                            " not writable by the daemon. Check its directory permissions; vpnctld writes there as the systemd-unit user (typically ",
                            " недоступен на запись демону. Проверь права на каталог; vpnctld пишет туда из-под пользователя systemd-юнита (обычно ",
                        ))
                        span.ed-mono { "user" } ")."
                    }
                }
            }
    }
        };
    render_page(&state, "settings", &theme, &accent, lang, body).await
}
