#!/usr/bin/env python3
"""Bundle CSS modules into daemon/assets/admin.css.

Usage:
    python3 scripts/bundle-css.py          # Write bundled CSS
    python3 scripts/bundle-css.py --check  # Verify admin.css is up-to-date
"""

import argparse
import difflib
from pathlib import Path
import sys

MODULES = [
    "fonts.css",
    "theme.css",
    "components.css",
    "charts.css",
]


def find_repo_root() -> Path:
    import subprocess
    try:
        out = subprocess.check_output(
            ["git", "rev-parse", "--show-toplevel"],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
        return Path(out).resolve()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return Path(__file__).resolve().parent.parent


def generate_bundle(css_dir: Path) -> str:
    chunks = [
        "/* ==========================================================================\n"
        " * vpnctl admin UI — bundled stylesheet (auto-generated by scripts/bundle-css.py)\n"
        " * Source modules live in daemon/assets/css/{fonts, theme, components, charts}.css\n"
        " * ========================================================================== */\n\n"
    ]
    for mod in MODULES:
        p = css_dir / mod
        if not p.exists():
            raise FileNotFoundError(f"Missing CSS module: {p}")
        header = (
            f"/* ─── MODULE: {mod} "
            f"{'─' * max(0, 65 - len(mod))} */\n"
        )
        chunks.append(header)
        chunks.append(p.read_text(encoding="utf-8").strip() + "\n\n")
    return "".join(chunks).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Bundle CSS modules")
    parser.add_argument("--check", action="store_true", help="Verify bundle is up-to-date")
    args = parser.parse_args()

    repo_root = find_repo_root()
    css_dir = repo_root / "daemon" / "assets" / "css"
    bundle_path = repo_root / "daemon" / "assets" / "admin.css"

    generated = generate_bundle(css_dir)

    if args.check:
        if not bundle_path.exists():
            print("Error: daemon/assets/admin.css does not exist", file=sys.stderr)
            return 1
        current = bundle_path.read_text(encoding="utf-8")
        if current != generated:
            print("Error: daemon/assets/admin.css is out of date.", file=sys.stderr)
            diff = difflib.unified_diff(
                current.splitlines(keepends=True),
                generated.splitlines(keepends=True),
                fromfile="daemon/assets/admin.css",
                tofile="generated",
                n=3,
            )
            sys.stderr.writelines(diff)
            print("\nRun `python3 scripts/bundle-css.py` to regenerate.", file=sys.stderr)
            return 1
        print("✔ daemon/assets/admin.css is up-to-date")
        return 0

    bundle_path.write_text(generated, encoding="utf-8")
    print("✔ Generated daemon/assets/admin.css from modules")
    return 0


if __name__ == "__main__":
    sys.exit(main())
